### PR TITLE
Fix Version being displayed when no version is given

### PR DESCRIPTION
**Pull request by roundedrectangle**

### CODE REVIEW

**Comment by ichthyosaurus** [comment]
Thank you! ::)

**Comment by roundedrectangle** [comment]
No problem! Thanks for making your module very flexible, I am using it in my messenger app multiple times (about the app and about the chat)

**Comment by ichthyosaurus** [comment]
Glad you like it, and it's really nice to see the module actually being used in other apps! I'm especially happy to see that it's actually flexible enough for special use cases like yours ([this](https://github.com/roundedrectangle/SailDiscord/blob/main/SailDiscord/qml/pages/AboutServerPage.qml)) - that kind of flexibility was my goal.

Can I add your app to the list [here](https://github.com/Pretty-SFOS/opal#apps-using-opal)?

**Comment by roundedrectangle** [comment]
Yeah that is ok

**Pull request merged**
